name = "render"
main = "src/index.ts"
compatibility_date = "2022-05-15"
# Set this to false if you don't want to use the default *.workers.dev route.
# Note that *.workers.dev routes don't support native worker-level caching: https://developers.cloudflare.com/workers/runtime-apis/cache/
workers_dev = true

[vars]
# The `cache-control` header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control. Optional, the `cache-control` header is omitted if unset.
CACHE_CONTROL = "max-age=86400"
# The string to prepend to each file path. Optional, nothing is prepended to the path if unset.
PATH_PREFIX = ""

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "img"         # Set this to your R2 bucket name. Required
preview_bucket_name = "img" # Set this to your preview R2 bucket name. Can be equal to bucket_name. Optional
